# Generated by Django 3.2.7 on 2021-10-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211014_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessiu',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
