# Generated by Django 3.2.7 on 2021-10-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tessiu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessiu',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
